database.url=jdbc:mysql://localhost:3306/g2rain_cms?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
database.driver=com.mysql.cj.jdbc.Driver
database.username=root
database.password=Sun_king18
project.basePackage=com.g2rain.cms
database.tables=web_site,article_category
tables.overwrite=false